<a href="https://colab.research.google.com/github/KuchkorovBoburbek/ai_foundation/blob/main/StudentPerformance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('StudentsPerformance.csv')

print("Dataset shape (rows, columns):",df.shape)

print("Column name:", df.columns.tolist())

print("First 5 rows of the dataset:")
print(df.head())

Dataset shape (rows, columns): (1000, 8)
Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [12]:

print("Summary Statistics:")
print(df.describe())

print("Data types and null info:")
print(df.info())

Summary Statistics:
       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000
Data types and null info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [13]:
print("Average score by columns:")
df[["math score", "reading score", "writing score"]].mean()

Average score by columns:

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [14]:

print("Maximum score by subject:")
df[["math score", "reading score", "writing score"]].max()

Maximum score by subject:

math score       100
reading score    100
writing score    100
dtype: int64

In [15]:

print("Minimum score by subject:")
df[["math score", "reading score", "writing score"]].min()

Minimum score by subject:

math score        0
reading score    17
writing score    10
dtype: int64

In [ ]:
# Correlation - bu ikkita data o‘rtasidagi bog‘liqlik darajasini aniqlash.
print("Correlation:")
df[["math score", "reading score", "writing score"]].corr()

In [17]:
# yangi feature
import numpy as np
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1) #
df["average score"] = df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")

print("New Columns preview (total, average, passed)")
print(df[["total score", "average score", "passed"]].head())

New Columns preview (total, average, passed)
   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes

In [ ]:
test_prep_group = df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()
print("Average scores by test preparation course:")
print(test_prep_group)

# gender based average
gender_group = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
print("Average scores by gender:")
print(gender_group)

# who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass rate:\n ", pass_rate)

In [18]:
# Convert Scores to Numpy Array
scores = df[["math score", "reading score", "writing score"]].values

# Mean, Std deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std Deviation:", np.std(scores, axis=0))

# Z-score (normalize qilish)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-score (Normalized numbers)")
print(z_score[:5])
# Average 0 | Negative - | Positive +

Numpy Mean: [66.089 69.169 68.054]
Numpy Std Deviation: [15.15549666 14.59289002 15.18805728]
Z-score (Normalized numbers)
[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]

In [19]:

# how many students scored above 90 average
top_scores = df[df["average score"] >= 90]
print("Top scored student above 90:", len(top_scores))

# how many failed?
failed = df[df["passed"] == "No"]
print("Failed from exam:", len(failed))

Top scored student above 90: 52
Failed from exam: 103